name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # Или ваша основная ветка

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Ruby and Jekyll 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Версия Ruby, совместимая с вашим Jekyll
          bundler-cache: true

      - name: Build Jekyll site ⚙️
        # Собираем сайт и указываем, что результат нужно положить в папку /blog
        run: JEKYLL_ENV=production bundle exec jekyll build --destination ./blog

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Публикуем ВЕСЬ репозиторий, включая папку /blog
          # keep_files: true # Раскомментируйте, если нужно сохранять файлы в ветке gh-pages